name: Go Waku Interop Tests

concurrency:
  group: Interop-tests
  cancel-in-progress: false

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches:
      - chore-custom-test-workflows
  workflow_dispatch:

jobs:
  call-multi-nim-common:
    uses: ./.github/workflows/test_common.yml
    with:
      node1: "harbor.status.im/wakuorg/go-waku:latest"
      node2: "harbor.status.im/wakuorg/go-waku:latest"



