name: On Demand Interop Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      node1:
        required: true
        description: "Node that usually publishes messages. Used for all tests"
        type: string
        default: "harbor.status.im/wakuorg/go-waku:latest"
      node2:
        required: true
        description: "Node that usually queries for published messages. Used for all tests"
        type: string
        default: "harbor.status.im/wakuorg/nwaku:latest"
      additional_nodes:
        required: false
        description: "Additional optional nodes used in e2e tests, separated by ,"
        type: string
        default: "harbor.status.im/wakuorg/nwaku:latest,harbor.status.im/wakuorg/go-waku:latest,harbor.status.im/wakuorg/nwaku:latest"

jobs:
  test-common:
    uses: ./.github/workflows/test_common.yml
    secrets: inherit
    with:
      node1: ${{ inputs.node1 }}
      node2: ${{ inputs.node2 }}
      additional_nodes: ${{ inputs.additional_nodes }}
