name: Nim -> Go Waku Interop Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  test-common:
    uses: ./.github/workflows/test_common.yml
    secrets: inherit
    with:
      node1: "wakuorg/nwaku:latest"
      node2: "wakuorg/go-waku:latest"
      caller: "go"
