name: Test Nim -> Nim Waku Interop Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - chore-rlnv2-tests-update
  workflow_dispatch:

jobs:
  test-common:
    uses: ./.github/workflows/test_common_test.yml
    secrets: inherit
    with:
      node1: "wakuorg/nwaku:latest"
      node2: "wakuorg/nwaku:latest"
      additional_nodes: "wakuorg/nwaku:latest,wakuorg/nwaku:latest,wakuorg/nwaku:latest"
      caller: "nim"
