name: Test Nim -> Nim Waku Interop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - 'fix-flaky-rln-test'
  workflow_dispatch:

jobs:
  test-common:
    uses: ./.github/workflows/test_common.yml
    secrets: inherit
    with:
      node1: "harbor.status.im/wakuorg/nwaku:latest"
      node2: "harbor.status.im/wakuorg/nwaku:latest"
      additional_nodes: "harbor.status.im/wakuorg/nwaku:latest,harbor.status.im/wakuorg/nwaku:latest,harbor.status.im/wakuorg/nwaku:latest"
      caller: "nim"
