name: Nim Waku RLN

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

on:
  push:
  workflow_dispatch:

jobs:
  test-common:
    uses: ./.github/workflows/test_common.yml
    secrets: inherit
    with:
      node1: "harbor.status.im/wakuorg/nwaku:latest"
      node2: "harbor.status.im/wakuorg/nwaku:latest"
      caller: "nim"
