name: Interop Tests

on:
  schedule:
    - cron:  '0 3 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      node1:
        required: false
        type: string
        default: "wakuorg/nwaku:deploy-wakuv2-test"
      node2:
        required: false
        type: string
        default: "wakuorg/go-waku:latest"

env:
  FORCE_COLOR: "1"
  NODE_1: ${{ inputs.node1 }}
  NODE_2: ${{ inputs.node2 }}

jobs:

  tests:
    name: Start self-hosted runners
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip' 
  
    - run: pip install -r requirements.txt

    - name: Run tests
      run: pytest
