name: Interop Tests

on:
  schedule:
    - cron:  '0 3 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      node1:
        required: false
        type: string
        default: "wakuorg/nwaku:latest"
      node2:
        required: false
        type: string
        default: "wakuorg/go-waku:latest"
      protocol:
        description: "Protocol used to comunicate inside the network"
        required: true
        type: choice
        default: "REST"
        options:
        - "REST"
        - "RPC"

env:
  FORCE_COLOR: "1"
  NODE_1: ${{ inputs.node1 }}
  NODE_2: ${{ inputs.node2 }}
  PROTOCOL: ${{ inputs.protocol || 'REST' }}

jobs:

  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip' 
  
    - run: pip install -r requirements.txt

    - name: Run tests
      run: pytest -n 4 --reruns 2 --alluredir=allure-results

    - name: Get allure history
      if: always()
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Setup allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_history: allure-history
        keep_reports: 30
  
    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
