
name: Interop Tests PR

on:
  workflow_call:
    inputs:
      node1:
        required: true
        type: string
        description: "Node that usually publishes messages. Used for all tests"
        default: "wakuorg/go-waku:latest"
      node2:
        required: true
        description: "Node that usually queries for published messages. Used for all tests"
        type: string
        default: "wakuorg/nwaku:latest"
      additional_nodes:
        required: false
        description: "Additional optional nodes used in e2e tests, separated by ,"
        type: string
        default: "wakuorg/nwaku:latest,wakuorg/go-waku:latest,wakuorg/nwaku:latest"
      caller:
        required: false
        description: "Workflow caller. Used in reporting"
        type: string

env:
  FORCE_COLOR: "1"
  NODE_1: ${{ inputs.node1 }}
  NODE_2: ${{ inputs.node2 }}
  ADDITIONAL_NODES: ${{ inputs.additional_nodes }}
  CALLER: ${{ inputs.caller || 'manual' }}
  RLN_CREDENTIALS: ${{ secrets.RLN_CREDENTIALS }}

jobs:

  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:

      - uses: actions/checkout@v4
        with:
          repository: waku-org/waku-interop-tests
          ref: SMOKE_TEST_0.0.1
      - uses: actions/setup-python@v4
        with:

          python-version: '3.12'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Run tests
        timeout-minutes: 30
        run: |
          pytest -m 'smoke' -n 4 --dist=loadgroup --reruns 1 --junit-xml=pytest_results.xml

      - name: Test Report
        if: always()
        uses: dorny/test-reporter@95058abb17504553158e70e2c058fe1fda4392c2
        with:
          name: Pytest JUnit Test Report
          path: pytest_results.xml
          reporter: java-junit
          use-actions-summary: 'true'

      - name: Create job summary
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
        run: |
          echo "## Run Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Event**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Actor**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Node1**: ${{ env.NODE_1 }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Node2**: ${{ env.NODE_2 }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Additonal Nodes**: ${{ env.ADDITIONAL_NODES }}" >> $GITHUB_STEP_SUMMARY
          if [ "$JOB_STATUS" != "success" ]; then
            echo "There are failures with nwaku node. cc <@&1111608257824440330>" >> $GITHUB_STEP_SUMMARY
          fi
          {
            echo 'JOB_SUMMARY<<EOF'
            cat $GITHUB_STEP_SUMMARY
            echo EOF
          } >> $GITHUB_ENV

    
