name: Interop Tests Common

on:
  workflow_call:
    inputs:
      node1:
        required: true
        description: "Node that usually publishes messages. Used for all tests"
        type: string
        default: "harbor.status.im/wakuorg/go-waku:latest"
      node2:
        required: true
        description: "Node that usually queries for published messages. Used for all tests"
        type: string
        default: "harbor.status.im/wakuorg/nwaku:latest"
      additional_nodes:
        required: false
        description: "Additional optional nodes used in e2e tests, separated by ,"
        type: string
        default: "harbor.status.im/wakuorg/nwaku:latest,harbor.status.im/wakuorg/go-waku:latest,harbor.status.im/wakuorg/nwaku:latest"


env:
  FORCE_COLOR: "1"
  NODE_1: ${{ inputs.node1 }}
  NODE_2: ${{ inputs.node2 }}
  ADDITIONAL_NODES: ${{ inputs.additional_nodes }}

jobs:

  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip' 
  
    - run: pip install -r requirements.txt

    - name: Create job summary
      if: always()
      id: job_summary
      run: |
        echo "## Run Information" >> $GITHUB_STEP_SUMMARY
        echo "SUMMARY=$(cat $GITHUB_STEP_SUMMARY)" >> $GITHUB_ENV

    - name: Send report to Discord
      uses: rjstone/discord-webhook-notify@v1
      if: always()
      with:
        severity: info
        username: ${{ github.workflow }}
        details: ${{ env.SUMMARY }}
        webhookUrl: ${{ secrets.DISCORD_TEST_REPORTS_WH }}
